### PR TITLE
AGDIGGER-128 Disable Gradle daemon

### PR DESCRIPTION
**Pull request by aliok**
JIRA: https://issues.jboss.org/browse/AGDIGGER-128

## Verification:
Build the image. ex:
`docker build . -t my-temp-image`

Use that image (my-temp-image) in Jenkins Kubernetes Android pod template. Build an Android application.

You should see this in the logs:
```
To honour the JVM settings for this build a new JVM will be forked. Please consider using the daemon: 
```

Unlike stated in JIRA, GRADLE_USER_HOME doesn't have to be set.

### CODE REVIEW

**Review by odra — APPROVED** [review]

**Review by matskiv — CHANGES_REQUESTED** [review]
I am seeing "Starting a Gradle Daemon (subsequent builds will be faster)" in log. This needs some investigation.

**Comment by aliok** [comment]
@matskiv added the missing `&&`

**Comment by aliok** [comment]
@matskiv please retest. I was able to verify the latest Dockerfile on OSM4.

**Comment by aliok** [comment]
Not merging this... See https://issues.jboss.org/browse/AGDIGGER-128

**Pull request closed without merging**
