### PR TITLE
AGDIGGER-131 Fix symlink to Android debug keystore

### PR DESCRIPTION
**Pull request by aliok**
### How to verify
1. Build the image, with a tag of your own choice
```
docker build . -t test-jenkins-android-slave
```

2. Change K8s config in Jenkins. Change Android slave image from "docker.io/aerogear/jenkins-android-slave:dev" to "test-jenkins-android-slave"

3. Build an application (you can use https://github.com/aliok/android25sampleapp.git if you don't have one handy). Download the artifact.

4. Do step #3 again.

5. Run this command for both APKs and check of they match (sample command on my machine):
```
/usr/local/Cellar/android-sdk/24.4.1_1/build-tools/25.0.2/apksigner verify --verbose --print-certs ~/Downloads/app-debug14.apk
```

6. Install the first APK on an Android device. Then, without removing it, install the 2nd one. You should be able to install the 2nd w/o problems.

### CODE REVIEW

**Review by aidenkeating — COMMENTED** [review]
LGTM :+1: Verifying now.

**Comment by aidenkeating** [comment]
Verified up to and including step 5. Can't do step 6 as I don't have a way to test it, @laurafitzgerald would you mind testing step 6?

**Comment by laurafitzgerald** [comment]
@aliok @aidenkeating :eyes:

**Comment by wei-lee** [comment]
@laurafitzgerald I am verifying this one now

**Comment by laurafitzgerald** [comment]
@wei-lee ok thanks. :)

**Comment by aliok** [comment]
@wei-lee do you mind pushing to DockerHub and testing again?

**Comment by wei-lee** [comment]
verified in osm4

**Pull request merged**
